### ISSUE TITLE
Open table fails on OSX 10.10.2

### ISSUE THREAD

**Issue by shulevski** [casacore/python-casacore#15] opened 2015-04-10 15:09 UTC
Attempt to open a table fails with:

```
File "/Library/Python/2.7/site-packages/python_casacore-2.0.0-py2.7-macosx-10.10-intel.egg/casacore/tables/table.py", line 311, in __init__
    Table.__init__ (self, tabname, lockopt, opt);
Boost.Python.ArgumentError: Python argument types in
    Table.__init__(table, str, dict, int)
did not match C++ signature:
    __init__(_object*, casa::String, casa::String, casa::String, bool, casa::IPosition, casa::String, casa::String, int, int, casa::Vector<casa::String>, casa::Vector<casa::String>)
    __init__(_object*, casa::String, casa::Record, casa::String, casa::String, int, casa::Record, casa::Record)
    __init__(_object*, std::__1::vector<casa::TableProxy, std::__1::allocator<casa::TableProxy> >, casa::Vector<casa::String>, int, int, int)
    __init__(_object*, casa::Vector<casa::String>, casa::Vector<casa::String>, casa::Record, int)
    __init__(_object*, casa::String, casa::Record, int)
    __init__(_object*, casa::String, std::__1::vector<casa::TableProxy, std::__1::allocator<casa::TableProxy> >)
    __init__(_object*, casa::TableProxy)
    __init__(_object*)
```

**Comment by tammojan** [comment] 2015-04-12 19:27
I can confirm that this is not a problem on linux (phew).

**Comment by tammojan** [comment] 2015-04-12 19:43
I'm guessing that the python argument ``table, str, dict, int`` should match ``_object*, casa::String, casa::Record, int``, so perhaps something wrong with the conversion from dict to record?

**Comment by gervandiepen** [comment] 2015-04-13 11:54
Are you sure the same libraries and a single version of them are used
everywhere, both during build and execution?
I know somebody built pyrap on OS-X, but boost-python had been built with a
different python version then pyrap causing this kind of problems.

Ger

**Comment by shulevski** [comment] 2015-04-13 12:41
Boost and boost-python were installed through homebrew. I get the following listings for them:

$ brew info boost-python
boost-python: stable 1.57.0, HEAD
http://www.boost.org
/usr/local/Cellar/boost-python/1.57.0 (5 files,  15M) *
  Built from source
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/boost-python.rb
==> Dependencies
Required: boost ✔
==> Options
--c++11
	Build using C++11 mode
--universal
	Build a universal binary
--with-python3
	Build with python3 support
--without-python
	Build without python support
--HEAD
	Install HEAD version

$ brew info boost
boost: stable 1.57.0 (bottled), HEAD
http://www.boost.org
/usr/local/Cellar/boost/1.57.0 (10572 files, 439M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/boost.rb
==> Dependencies
Optional: icu4c ✘
==> Options
--c++11
	Build using C++11 mode
--universal
	Build a universal binary
--with-icu4c
	Build regexp engine with icu support
--with-mpi
	Build with MPI support
--without-single
	Disable building single-threading variant
--without-static
	Disable building static library variant
--HEAD
	Install HEAD version

Boost-python is built with python3 support, but I am not sure whether that is causing the issue.

**Comment by gervandiepen** [comment] 2015-04-13 14:09
python-casacore is not python3 ready yet, so indeed that might be a
problem. I've never tried this.

**Comment by tammojan** [comment] 2015-04-13 19:31
This issue is probably linked with this one: https://code.google.com/p/pyrap/issues/detail?id=20 (probably the one Ger is referring to). Unfortunately, the fix given was specific to the scons build system, which is not used in python-casacore.

My system has the same error, and I didn't do anything funny with Python. In particular, I didn't install a brew Python, so there should be only one Python interpreter on the system. I'll investigate further...

**Comment by tammojan** [comment] 2015-04-13 19:47
Not sure that the python version is the problem. The following snippet shows that libboost-python is linked against python 2.7:
```
$ otool -L `brew list boost-python | grep python-mt.dylib`
/usr/local/Cellar/boost-python/1.57.0/lib/libboost_python-mt.dylib:
	/usr/local/lib/libboost_python-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/System/Library/Frameworks/Python.framework/Versions/2.7/Python (compatibility version 2.7.0, current version 2.7.6)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
```
And indeed, I'm using python 2.7:
```
$ python --version
Python 2.7.6
```

**Comment by shulevski** [comment] 2015-04-13 21:50
I have the same output on my system as shown by tammojan above.

**Comment by ludwigschwardt** [comment] 2015-04-17 08:46
Hi @tammojan and @shulevski,

I've reproduced this on my Mavericks + Homebrew system.

I don't think it's a Python version issue. Both of you only have System Python and that's what's correctly linked. Mine's actually worse, as brew python and system python are mixed together - but that's another problem :-)

It's also not the same as the pyrap error I described before.

On the other hand, my current pyrap brew formula stills compiles and works with the latest casacore 2.0.1, and pyrap is almost equal to python-casacore, so maybe I should apply my old pyrap patches to python-casacore and see what happens.

**Comment by tammojan** [comment] 2015-04-17 16:56
Hi @ludwigschwardt, if it is not the bug of your old pyrap ticket, then perhaps applying the patches won't work. But please do go ahead! I'll check as well with @gervandiepen if it is boost-python + llvm related.

**Comment by tammojan** [comment] 2015-05-10 19:52
@ludwigschwardt Any news on this?

**Comment by tammojan** [comment] 2015-08-03 19:59
The following output from the compilation of `python-casacore` could perhaps be the culprit:
```
ld: warning: ignoring file /Users/tammo/opt/casacore/github/lib//libcasa_scimath.dylib, file was built for x86_64 which is not the architecture being linked (i386): /Users/tammo/opt/casacore/github/lib//libcasa_scimath.dylib
```
@gijzelaerr Do you have any idea why the architecture being linked is not x86_64?

**Comment by tammojan** [comment] 2015-08-04 08:15
Haha, found the bug! It turns out that casacore was linked to `boost_python-mt` (even though USE_THREADS was NO) and python-casacore was linked to `boost_python`. I'll think of a way to auto-detect this.

**Comment by ludwigschwardt** [comment] 2015-08-04 11:28
Of course it would be nice if casacore had no Python dependencies of its
own, leaving it all to python-casacore as the name indicates...

Just my three cents!

L.


On Tue, Aug 4, 2015 at 10:15 AM, Tammo Jan Dijkema <notifications@github.com

**Comment by gijzelaerr** [comment] 2015-08-04 11:35
we had this discussion before in the proximity of a coffee machine ;)

I agree it would be more pretty, but python-casacore is now pure setuptools, which is nice since it is now pipable. Finding boost with setuptools is not really pretty, cmake is much better at this. So in the end I think this is the least ugly solution.

So unless you know a pretty way of finding boost and configuring build dependencies with setuptools, or have an even better solution, this is not going to change.

**Comment by ludwigschwardt** [comment] 2015-08-04 11:43
Oh yes, there was that - thanks for reminding me! I will have some more
thoughts on this.

**Comment by tammojan** [comment] 2015-08-04 12:31
@ludwigschwardt While we think of a proper fix, do you know how to do something like `if os == "osx" : boost_python='boost_python-md'` in `setup.py`?

**Comment by gijzelaerr** [comment] 2015-08-04 13:22
https://docs.python.org/2/library/platform.html

2015-08-04 14:31 GMT+02:00 Tammo Jan Dijkema <notifications@github.com>:

> @ludwigschwardt <https://github.com/ludwigschwardt> While we think of a
> proper fix, do you know how to do something like if os == "osx" :
> boost_python='boost_python-md' in setup.py?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/casacore/python-casacore/issues/15#issuecomment-127585441>
> .
>



-- 
Gijs Molenaar
http://pythonic.nl

**Comment by ludwigschwardt** [comment] 2015-08-04 13:27
Indeed! My response time is currently slow due to a day old baby :-)

**Comment by tammojan** [comment] 2015-08-04 13:32
> My response time is currently slow due to a day old baby :-)

A valid excuse, I'd say. Congratulations! Am I the first to congratulate you in a github issue?

**Comment by shulevski** [comment] 2015-08-04 14:16
If you are the first, I am going to be the second :) Congrats! I am moving
house, but as soon as we have a patch, I will test the install.

**Comment by gijzelaerr** [comment] 2015-08-04 14:18
congrats bru!

can't wait to see his/her first pull request.

**Comment by ludwigschwardt** [comment] 2015-08-04 14:35
Thanks guys! Gijs, I'll try to make sure that you don't wait more than a
decade... :-)

**Comment by tammojan** [comment] 2015-11-23 09:46
Still not solved everywhere:
```
MacDijkema:tim dijkema$ python
Python 2.7.10 (default, Jul 13 2015, 12:05:58)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyrap.tables as pt
>>> t=pt.table('tim-3.MS')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dijkema/opt/python-casacore/src/casacore/tables/table.py", line 311, in __init__
    Table.__init__ (self, tabname, lockopt, opt);
TypeError: Expecting an object of type dict; got an object of type dict instead
>>>
```

**Comment by tammojan** [comment] 2015-11-23 09:46
With casacore master and python-casacore master.

**Comment by gijzelaerr** [comment] 2015-11-23 09:54
that looks like a different issue though, and I've seen this before:

https://code.google.com/p/pyrap/issues/detail?id=20

**Comment by tammojan** [comment] 2015-11-23 09:58
Yuk, I was using the homebrew python instead of the system one, which is asking for problems.

Still, the message could be clearer..

Closing the issue for now.

**Closed by tammojan** 2015-11-23 09:58 UTC
Labels: bug
